name: Node.js CI/CD with MongoDB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Deploy to production
      if: success()
      run: |
        # This is where you would deploy your application to production
        # For example, you might use a service like Heroku or AWS Elastic Beanstalk
        # You'll need to set up secrets in your GitHub repository for deployment

    - name: Deploy to staging
      if: success()
      run: |
        # This is where you would deploy your application to a staging environment
        # For example, you might use a different Heroku app or a staging server
        # You'll need to set up secrets in your GitHub repository for deployment