version: 2.1

jobs:
  trivy:
    docker:
      - image: aquasec/trivy:latest
    working_directory: /tmp/workspace
    environment:
      ENV_FILE: /tmp/workspace/
      DOCKER_BUILDKIT: "1"
      BUILDKIT_PROGRESS: plain
    steps:
      - checkout
      - attach_workspace:
         at: /tmp/workspace
      - setup_remote_docker:
          version: 20.10.7     
          docker_layer_caching: true   

      - run:
          name: Install trivy
          command: |
            apk add --update-cache --upgrade --update curl
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          
      - run:
          name: Run Trivy Scan
          command: |
           trivy fs --scanners vuln,secret,config --severity HIGH,CRITICAL,LOW ./modules/  > trivy_output.txt

      # Upload the output file to CircleCI artifacts
      - store_artifacts:
          path: trivy_output.txt
          destination: trivy_output

workflows:
  version: 2
  trivy-terraform:
    jobs:
      - trivy