apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: delete-workflows
  namespace: argo
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: delete-workflows
            template: delete-workflows
    - name: delete-workflows
      container:
        image: "YOUR DELETE WORKFLOWS IMAGE"
        command: ["python", "script.py"]